import Head from "next/head";
import { Heading, Text, Flex, Box, Image, HStack } from "@chakra-ui/react";

export default function About() {
  return (
    <>
      <Head>
        <title>Smash Camp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        height="100%"
        overflow="auto"
        as="main"
        color="whiteAlpha.900"
        bg="linear-gradient(#191970, #9967A4, #C46E9D, #F48D86, #FEBC64, #FFDD5A)"
      >
        <Heading
          as="h1"
          size="6xl"
          noOfLines={1}
          Text
          fontSize="6xl"
          color="tomato"
          textAlign="center"
        >
          About
        </Heading>
        <p>
          This app was developed by a team of dedicated, gamers from the Boys &
          Girls Club of the Umpqua Valley. The app was created to help Smash
          Bros. Ultimate playres from around the world, regardless of skill,
          level up their game.
        </p>
        <br></br>
        <p>Contact Us At:</p>
        <p>Email@email.com</p>
        <br></br>
        <p>Support Us</p>
        <p>Help support our Club and this app by making a donation.</p>
        <br></br>
        <Flex>
          <Box>
            <Text>Money!</Text>
            <Image
              alt=""
              boxSize="50px"
              src="https://cdn-icons-png.flaticon.com/512/3362/3362189.png"
            />
          </Box>
          <Box>
            <Text>Pizza!</Text>
            <Image
              alt=""
              boxSize="50px"
              src="https://cdn.icon-icons.com/icons2/2113/PNG/512/pizza_icon_131067.png"
            />
          </Box>
          <Box>
            <Text>Coffee!</Text>
            <Image
              alt=""
              boxSize="50px"
              src="https://cdn-icons-png.flaticon.com/512/3127/3127336.png"
            />
          </Box>
        </Flex>
      </Box>
    </>
  );
}
