import { Box, Heading, Image, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Smash Bros Ultimate Trainer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        color="whiteAlpha.900"
        as="main"
        height="100%"
        bgGradient="linear(#191970, #9967A4, #C46E9D, #F48D86, #FEBC64, #FFDD5A)"
      >
        <Heading>Smash Bros Ultimate Trainer</Heading>
        <Text>
          This app is here to help you get better at Smash Bros Ultimate!
        </Text>
        <Image
          postion="absolute"
          top="100px"
          left="200px"
          src="https://static.wikia.nocookie.net/mario/images/4/41/SMPBowserJr.png"
        />
        <Image
          position="absolute"
          top="100px"
          left="200px"
          src="https://ssb.wiki.gallery/images/thumb/0/07/Kirby_SSBU.png/250px-Kirby_SSBU.png"
        />
      </Box>
    </>
  );
}
