import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Nav from "@/components/Nav";
export default function Tips() {
  return (
    <>
      <Head>
        <title>Smash Camp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        height="100%"
        overflow="auto"
        as="main"
        color="whiteAlpha.900"
        bg="linear-gradient(#191970, #9967A4, #C46E9D, #F48D86, #FEBC64, #FFDD5A)"
      ></Box>
      <Nav left="" right="tier-list" />
    </>
  );
}
